import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";
import { HomeIcon } from "lucide-react";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <nav className="bg-sky-950 text-white p-5 h-24 flex items-center justify-between z-10 relative">
            <Link
              href="/"
              className="text-3xl tracking-wide flex gap-2 items-center uppercase"
            >
              <HomeIcon />

              <p className="mb-0.5 font-[500]">V Homes</p>
            </Link>
            <ul className="flex gap-8 items-center">
              <li>
                <Link
                  href="/property-search"
                  className="uppercase tracking-wide hover:underline"
                >
                  Property search
                </Link>
              </li>
              <li>
                <AuthButtons />{" "}
              </li>
            </ul>
          </nav>
          {children}
          <Toaster closeButton richColors={true} />
        </AuthProvider>
      </body>
    </html>
  );
}
